const AUTH0_CLIENT_ID = process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID;
const AUTH0_CLIENT_SECRET = process.env.AUTH0_CLIENT_SECRET;
const AUTH0_SCOPE = process.env.NEXT_PUBLIC_AUTH0_SCOPE;
const AUTH0_DOMAIN = process.env.NEXT_PUBLIC_AUTH0_DOMAIN;
const REDIRECT_URI = process.env.NEXT_PUBLIC_REDIRECT_URI;
const POST_LOGOUT_REDIRECT_URI =
  process.env.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI;
const SESSION_COOKIE_SECRET = process.env.SESSION_COOKIE_SECRET;
const SESSION_COOKIE_LIFETIME = process.env.SESSION_COOKIE_LIFETIME;

module.exports = {
  AUTH0_CLIENT_ID,
  AUTH0_CLIENT_SECRET,
  AUTH0_SCOPE,
  AUTH0_DOMAIN,
  REDIRECT_URI,
  POST_LOGOUT_REDIRECT_URI,
  SESSION_COOKIE_SECRET,
  SESSION_COOKIE_LIFETIME,
};
